CREATE TABLE tb_cash_sina (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(20), -- '股票代码',
    report_date VARCHAR(8) , -- '报告日',
    operating_cash_flow DECIMAL(20,2) , -- '经营活动产生的现金流量',
    cash_from_sales DECIMAL(20,2) , -- '销售商品、提供劳务收到的现金',
    net_increase_in_customer_deposits DECIMAL(20,2) , -- '客户存款和同业存放款项净增加额',
    net_increase_in_central_bank_borrowing DECIMAL(20,2) , -- '向中央银行借款净增加额',
    net_increase_in_interbank_borrowing DECIMAL(20,2) , -- '向其他金融机构拆入资金净增加额',
    cash_from_insurance_premiums DECIMAL(20,2) , -- '收到原保险合同保费取得的现金',
    net_cash_from_reinsurance DECIMAL(20,2) , -- '收到再保险业务现金净额',
    net_increase_in_policyholder_deposits DECIMAL(20,2) , -- '保户储金及投资款净增加额',
    net_increase_in_trading_securities DECIMAL(20,2) , -- '处置交易性金融资产净增加额',
    cash_from_interest_fees_commissions DECIMAL(20,2) , -- '收取利息、手续费及佣金的现金',
    net_increase_in_borrowed_funds DECIMAL(20,2) , -- '拆入资金净增加额',
    net_increase_in_repurchase_funds DECIMAL(20,2) , -- '回购业务资金净增加额',
    tax_refunds_received DECIMAL(20,2) , -- '收到的税费返还',
    other_operating_cash_inflows DECIMAL(20,2) , -- '收到的其他与经营活动有关的现金',
    total_operating_cash_inflows DECIMAL(20,2) , -- '经营活动现金流入小计',
    cash_paid_for_goods_services DECIMAL(20,2) , -- '购买商品、接受劳务支付的现金',
    net_increase_in_customer_loans DECIMAL(20,2) , -- '客户贷款及垫款净增加额',
    net_increase_in_central_bank_deposits DECIMAL(20,2) , -- '存放中央银行和同业款项净增加额',
    cash_paid_for_insurance_claims DECIMAL(20,2) , -- '支付原保险合同赔付款项的现金',
    cash_paid_for_interest_fees_commissions DECIMAL(20,2) , -- '支付利息、手续费及佣金的现金',
    cash_paid_for_policy_dividends DECIMAL(20,2) , -- '支付保单红利的现金',
    cash_paid_to_employees DECIMAL(20,2) , -- '支付给职工以及为职工支付的现金',
    taxes_paid DECIMAL(20,2) , -- '支付的各项税费',
    other_operating_cash_outflows DECIMAL(20,2) , -- '支付的其他与经营活动有关的现金',
    total_operating_cash_outflows DECIMAL(20,2) , -- '经营活动现金流出小计',
    net_operating_cash_flow DECIMAL(20,2) , -- '经营活动产生的现金流量净额',
    investing_cash_flow DECIMAL(20,2) , -- '投资活动产生的现金流量',
    cash_from_investment_recovery DECIMAL(20,2) , -- '收回投资所收到的现金',
    cash_from_investment_returns DECIMAL(20,2) , -- '取得投资收益收到的现金',
    cash_from_asset_disposal DECIMAL(20,2) , -- '处置固定资产、无形资产和其他长期资产所收回的现金净额',
    cash_from_subsidiary_disposal DECIMAL(20,2) , -- '处置子公司及其他营业单位收到的现金净额',
    other_investing_cash_inflows DECIMAL(20,2) , -- '收到的其他与投资活动有关的现金',
    cash_from_reduced_deposits DECIMAL(20,2) , -- '减少质押和定期存款所收到的现金',
    net_increase_in_available_for_sale_securities DECIMAL(20,2) , -- '处置可供出售金融资产净增加额',
    total_investing_cash_inflows DECIMAL(20,2) , -- '投资活动现金流入小计',
    cash_paid_for_assets DECIMAL(20,2) , -- '购建固定资产、无形资产和其他长期资产所支付的现金',
    cash_paid_for_investments DECIMAL(20,2) , -- '投资所支付的现金',
    net_increase_in_pledged_loans DECIMAL(20,2) , -- '质押贷款净增加额',
    cash_paid_for_subsidiary_acquisition DECIMAL(20,2) , -- '取得子公司及其他营业单位支付的现金净额',
    cash_paid_for_increased_deposits DECIMAL(20,2) , -- '增加质押和定期存款所支付的现金',
    other_investing_cash_outflows DECIMAL(20,2) , -- '支付的其他与投资活动有关的现金',
    total_investing_cash_outflows DECIMAL(20,2) , -- '投资活动现金流出小计',
    net_investing_cash_flow DECIMAL(20,2) , -- '投资活动产生的现金流量净额',
    financing_cash_flow DECIMAL(20,2) , -- '筹资活动产生的现金流量',
    cash_from_equity_financing DECIMAL(20,2) , -- '吸收投资收到的现金',
    cash_from_minority_investment DECIMAL(20,2) , -- '子公司吸收少数股东投资收到的现金',
    cash_from_borrowing DECIMAL(20,2) , -- '取得借款收到的现金',
    cash_from_bond_issuance DECIMAL(20,2) , -- '发行债券收到的现金',
    other_financing_cash_inflows DECIMAL(20,2) , -- '收到其他与筹资活动有关的现金',
    total_financing_cash_inflows DECIMAL(20,2) , -- '筹资活动现金流入小计',
    cash_paid_for_debt_repayment DECIMAL(20,2) , -- '偿还债务支付的现金',
    cash_paid_for_dividends_interest DECIMAL(20,2) , -- '分配股利、利润或偿付利息所支付的现金',
    cash_paid_to_minority_shareholders DECIMAL(20,2) , -- '子公司支付给少数股东的股利、利润',
    other_financing_cash_outflows DECIMAL(20,2) , -- '支付其他与筹资活动有关的现金',
    total_financing_cash_outflows DECIMAL(20,2) , -- '筹资活动现金流出小计',
    net_financing_cash_flow DECIMAL(20,2) , -- '筹资活动产生的现金流量净额',
    exchange_rate_effect DECIMAL(20,2) , -- '汇率变动对现金及现金等价物的影响',
    net_cash_increase DECIMAL(20,2) , -- '现金及现金等价物净增加额',
    beginning_cash_balance DECIMAL(20,2) , -- '期初现金及现金等价物余额',
    ending_cash_balance_cash DECIMAL(20,2) , -- '现金的期末余额',
    beginning_cash_balance_cash DECIMAL(20,2) , -- '现金的期初余额',
    ending_cash_equivalents_balance DECIMAL(20,2) , -- '现金等价物的期末余额',
    beginning_cash_equivalents_balance DECIMAL(20,2) , -- '现金等价物的期初余额',
    ending_total_cash_balance DECIMAL(20,2) , -- '期末现金及现金等价物余额',
    data_source VARCHAR(50) , -- '数据源',
    is_audited VARCHAR(10) , -- '是否审计',
    announcement_date VARCHAR(8) , -- '公告日期',
    currency VARCHAR(10) , -- '币种',
    report_type VARCHAR(50) , -- '类型',
    update_date TIMESTAMP , -- '更新日期',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- '创建时间'
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- '更新时间'
    is_deleted BOOLEAN DEFAULT FALSE -- '是否删除'
);

CREATE INDEX idx_ticker_report_date ON tb_cash_sina (ticker, report_date);