CREATE TABLE IF NOT EXISTS tb_profit_sina (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10), -- '股票代码',
    report_date VARCHAR(8) , -- '报告日',
    total_operating_revenue DECIMAL(15,2) , -- '营业总收入',
    operating_revenue DECIMAL(15,2) , -- '营业收入',
    interest_income DECIMAL(15,2) , -- '利息收入',
    earned_premium DECIMAL(15,2) , -- '已赚保费',
    commission_income DECIMAL(15,2) , -- '手续费及佣金收入',
    real_estate_sales_revenue DECIMAL(15,2) , -- '房地产销售收入',
    other_business_revenue DECIMAL(15,2) , -- '其他业务收入',
    total_operating_cost DECIMAL(15,2) , -- '营业总成本',
    operating_cost DECIMAL(15,2) , -- '营业成本',
    commission_expense DECIMAL(15,2) , -- '手续费及佣金支出',
    real_estate_sales_cost DECIMAL(15,2) , -- '房地产销售成本',
    surrender_value DECIMAL(15,2) , -- '退保金',
    net_compensation_expense DECIMAL(15,2) , -- '赔付支出净额',
    net_insurance_contract_reserves DECIMAL(15,2) , -- '提取保险合同准备金净额',
    policy_dividend_expense DECIMAL(15,2) , -- '保单红利支出',
    reinsurance_expense DECIMAL(15,2) , -- '分保费用',
    other_business_cost DECIMAL(15,2) , -- '其他业务成本',
    business_tax_and_surcharge DECIMAL(15,2) , -- '营业税金及附加',
    rd_expense DECIMAL(15,2) , -- '研发费用',
    sales_expense DECIMAL(15,2) , -- '销售费用',
    management_expense DECIMAL(15,2) , -- '管理费用',
    financial_expense DECIMAL(15,2) , -- '财务费用',
    interest_expense DECIMAL(15,2) , -- '利息费用',
    interest_expenditure DECIMAL(15,2) , -- '利息支出',
    investment_income DECIMAL(15,2) , -- '投资收益',
    investment_income_associates DECIMAL(15,2) , -- '对联营企业和合营企业的投资收益',
    financial_asset_termination_income DECIMAL(15,2) , -- '以摊余成本计量的金融资产终止确认产生的收益',
    exchange_gain DECIMAL(15,2) , -- '汇兑收益',
    net_exposure_hedge_income DECIMAL(15,2) , -- '净敞口套期收益',
    fair_value_change_income DECIMAL(15,2) , -- '公允价值变动收益',
    futures_profit_loss DECIMAL(15,2) , -- '期货损益',
    custody_income DECIMAL(15,2) , -- '托管收益',
    subsidy_income DECIMAL(15,2) , -- '补贴收入',
    other_income DECIMAL(15,2) , -- '其他收益',
    asset_impairment_loss DECIMAL(15,2) , -- '资产减值损失',
    credit_impairment_loss DECIMAL(15,2) , -- '信用减值损失',
    other_business_profit DECIMAL(15,2) , -- '其他业务利润',
    asset_disposal_income DECIMAL(15,2) , -- '资产处置收益',
    operating_profit DECIMAL(15,2) , -- '营业利润',
    non_operating_income DECIMAL(15,2) , -- '营业外收入',
    non_current_asset_disposal_gain DECIMAL(15,2) , -- '非流动资产处置利得',
    non_operating_expense DECIMAL(15,2) , -- '营业外支出',
    non_current_asset_disposal_loss DECIMAL(15,2) , -- '非流动资产处置损失',
    total_profit DECIMAL(15,2) , -- '利润总额',
    income_tax_expense DECIMAL(15,2) , -- '所得税费用',
    unrecognized_investment_loss DECIMAL(15,2) , -- '未确认投资损失',
    net_profit DECIMAL(15,2) , -- '净利润',
    continuing_operation_net_profit DECIMAL(15,2) , -- '持续经营净利润',
    discontinued_operation_net_profit DECIMAL(15,2) , -- '终止经营净利润',
    net_profit_parent_company DECIMAL(15,2) , -- '归属于母公司所有者的净利润',
    merged_party_net_profit DECIMAL(15,2) , -- '被合并方在合并前实现净利润',
    minority_profit_loss DECIMAL(15,2) , -- '少数股东损益',
    other_comprehensive_income DECIMAL(15,2) , -- '其他综合收益',
    other_comprehensive_income_parent DECIMAL(15,2) , -- '归属于母公司所有者的其他综合收益',
    non_reclassifiable_comprehensive_income DECIMAL(15,2) , -- '以后不能重分类进损益的其他综合收益',
    benefit_plan_change DECIMAL(15,2) , -- '重新计量设定受益计划变动额',
    equity_method_non_reclassifiable DECIMAL(15,2) , -- '权益法下不能转损益的其他综合收益',
    equity_instrument_fair_value_change DECIMAL(15,2) , -- '其他权益工具投资公允价值变动',
    own_credit_risk_fair_value_change DECIMAL(15,2) , -- '企业自身信用风险公允价值变动',
    reclassifiable_comprehensive_income DECIMAL(15,2) , -- '以后将重分类进损益的其他综合收益',
    equity_method_reclassifiable DECIMAL(15,2) , -- '权益法下可转损益的其他综合收益',
    available_for_sale_fair_value_change DECIMAL(15,2) , -- '可供出售金融资产公允价值变动损益',
    debt_investment_fair_value_change DECIMAL(15,2) , -- '其他债权投资公允价值变动',
    financial_asset_reclassification DECIMAL(15,2) , -- '金融资产重分类计入其他综合收益的金额',
    debt_investment_credit_impairment DECIMAL(15,2) , -- '其他债权投资信用减值准备',
    held_to_maturity_reclassification DECIMAL(15,2) , -- '持有至到期投资重分类为可供出售金融资产损益',
    cash_flow_hedge_reserve DECIMAL(15,2) , -- '现金流量套期储备',
    cash_flow_hedge_effective_portion DECIMAL(15,2) , -- '现金流量套期损益的有效部分',
    foreign_currency_translation DECIMAL(15,2) , -- '外币财务报表折算差额',
    other_items DECIMAL(15,2) , -- '其他',
    minority_other_comprehensive_income DECIMAL(15,2) , -- '归属于少数股东的其他综合收益',
    total_comprehensive_income DECIMAL(15,2) , -- '综合收益总额',
    total_comprehensive_income_parent DECIMAL(15,2) , -- '归属于母公司所有者的综合收益总额',
    minority_comprehensive_income DECIMAL(15,2) , -- '归属于少数股东的综合收益总额',
    basic_eps DECIMAL(10,4) , -- '基本每股收益',
    diluted_eps DECIMAL(10,4) , -- '稀释每股收益',
    data_source VARCHAR(50) , -- '数据源',
    is_audited VARCHAR(20) , -- '是否审计',
    announcement_date VARCHAR(8) , -- '公告日期',
    currency VARCHAR(10) , -- '币种',
    report_type VARCHAR(50) , -- '类型',
    update_date TIMESTAMP,  -- '更新日期',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- '创建时间'
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- '更新时间'
    is_deleted BOOLEAN DEFAULT FALSE -- '是否删除'
);

CREATE INDEX idx_ticker_report_date ON tb_profit_sina (ticker, report_date);
